### ISSUE TITLE
Not working in Ubuntu 14.04, Sublime 2.0.2, Build 2221

### ISSUE THREAD

**Issue by formigone** [rexxars/sublime-hacker-typer#3]
I just found this awesome plugin today, and this is the first time I've ever touched Sublime. It could well be that I'm just too ignorant to figure this out on my own, so I apologize ahead of time.

I have installed the package and enabled the plugin. If I open a file that doesn't have an accompanying *.hackertyper solution, I get the error message on the notification bar at the bottom. If I open a blank file whose filename matches its solution, I start editing the file, but I only see what I'm typing.

```
// file: test.html.hackertyper
<!doctype html>
<html>
...
</html>
```

```
// file: test.html
(blank file)
```

Any ideas?

**Comment by rexxars** [comment]
I have not tested this on Sublime text 2, so I'm not sure if it's going to work there - probably not.
Sorry about that, should probably make a note that this plugin only works on Sublime Text 3.

**Comment by formigone** [comment]
Thanks for your reply. Very helpful. Awesome plugin!
